<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;


class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $names = [
            "山崎　励",
            "森田　千恵",
            "大庭　香奈",
            "井浦　容子",
            "副島　直行",
            "酒井　久志",
            "後藤　健",
            "山口　敬之",
            "高橋　輝明",
            "齋藤　新悟",
            "向井　兼司",
            "三輪　卓",
            "津田　宏和",
            "上出　理恵",
            "飯田　尚弘",
            "石井　佳之",
            "谷本　鮎美",
            "北島　克也",
            "松田　よしこ",
            "松井　詩織",
            "竹内　雅貴",
            "岡本　周平",
            "奥村　倫子",
            "正木　佑弥",
            "田中　美枝",
            "稲垣　章",
            "荒川　博文",
            "岡田　雅明",
            "渡辺　哲也",
            "勝俣　文俊",
            "安井　晋太郎",
            "萱沼　亜矢",
            "土屋　智徳",
            "宮本　基",
            "中島　寛司",
            "田沼　淳也",
            "田中　真以",
            "佐藤　晋一",
            "本村　幹夫",
            "木ノ本　綾野",
            "島本　忍",
            "内藤　智幸",
            "丸木　一之",
            "直江　竜輔",
            "有賀　茂之",
            "内山　秀男",
            "金森　智子",
            "八田　武",
            "山田　浩平",
            "小島　和徳"
        ];

        $furiganas = [
            "ヤマザキ　ツトム",
            "モリタ　チエ",
            "オオバ　カナ",
            "イウラ　ヒロコ",
            "ソエジマ　ナオユキ",
            "サカイ　ヒサシ",
            "ゴトウ　ケン",
            "ヤマグチ　タカユキ",
            "タカハシ　テルアキ",
            "サイトウ　シンゴ",
            "ムカイ　ケンジ",
            "ミワ　スグル",
            "ツダ　ヒロカズ",
            "カミデ　リエ",
            "イイダ　ナオヒロ",
            "イシイ　ヨシユキ",
            "タニモト　アユミ",
            "キタジマ　カツヤ",
            "マツダ　ヨシコ",
            "マツイ　シオリ",
            "タケウチ　マサキ",
            "オカモト　シュウヘイ",
            "オクムラ　ノリコ",
            "マサキ　ユウヤ",
            "タナカ　ミエ",
            "イナガキ　アキラ",
            "アラカワ　ヒロフミ",
            "オカダ　マサアキ",
            "ワタナベ　テツヤ",
            "カツマタ　フミトシ",
            "ヤスイ　シンタロウ",
            "カヤヌマ　アヤ",
            "ツチヤ　トモノリ",
            "ミヤモト　モトイ",
            "ナカジマ　カンジ",
            "タヌマ　ジュンヤ",
            "タナカ　マイ",
            "サトウ　シンイチ",
            "モトムラ　ミキオ",
            "キノモト　アヤノ",
            "シマモト　シノブ",
            "ナイトウ　トモユキ",
            "マルキ　カズユキ",
            "ナオエ　リュウスケ",
            "アリガ　シゲユキ",
            "ウチヤマ　ヒデオ",
            "カナモリ　トモコ",
            "ハッタ　タケル",
            "ヤマダ　コウヘイ",
            "コジマ　カズノリ"
        ];

        $emails = [
            "yamazakitsutomu@example.co.jp",
            "morita104@example.ne.jp",
            "oba524@example.ne.jp",
            "iurahiroko@example.net",
            "naoyukisoejima@example.net",
            "sakai_105@example.co.jp",
            "ken_goto@example.co.jp",
            "takayuki_yamaguchi@example.ne.jp",
            "takahashi_teruaki@example.ne.jp",
            "saito_shingo@example.org",
            "kenji_mukai@example.jp",
            "miwasuguru@example.ne.jp",
            "hirokazutsuda@example.org",
            "kamide1213@example.ne.jp",
            "iida_naohiro@example.net",
            "ishiiyoshiyuki@example.org",
            "tanimoto_ayumi@example.co.jp",
            "katsuyakitajima@example.jp",
            "matsuda_1022@example.com",
            "matsuishiori@example.net",
            "takeuchi_1018@example.com",
            "shuuheiokamoto@example.ne.jp",
            "norikookumura@example.net",
            "masaki428@example.jp",
            "mietanaka@example.ne.jp",
            "inagaki_629@example.jp",
            "hirofumiarakawa@example.net",
            "okada630@example.com",
            "watanabe131@example.ne.jp",
            "katsumata41@example.org",
            "shintarou_yasui@example.net",
            "ayakayanuma@example.co.jp",
            "tsuchiyatomonori@example.com",
            "miyamoto_motoi@example.net",
            "nakajima_kanji@example.co.jp",
            "junya_tanuma@example.com",
            "tanaka614@example.jp",
            "shinichisato@example.net",
            "mikio_motomura@example.net",
            "kinomoto_ayano@example.co.jp",
            "shimamotoshinobu@example.com",
            "naitotomoyuki@example.org",
            "maruki_1213@example.jp",
            "naoeryuusuke@example.org",
            "shigeyukiariga@example.net",
            "uchiyama_hideo@example.org",
            "kanamori_1122@example.ne.jp",
            "hattatakeru@example.ne.jp",
            "yamada_111@example.com",
            "kojima_629@example.com"
        ];

        $passwords = [
            "CzVMxvO4",
            "ZwAIY5DI",
            "1ae7Ucxq",
            "z1eZDEbL",
            "mX4KlzdL",
            "JdfOWXk6",
            "JpbeT83K",
            "WPNWRn7E",
            "SeSuI28N",
            "67xYHJ27",
            "TnoShRco",
            "OjO4MVw2",
            "ILZZQOCv",
            "Xo1xcdrE",
            "gY7wDibo",
            "eppDBfqB",
            "KQA1WJIM",
            "5hgsX6XT",
            "pvuDRjoG",
            "wtnGFepq",
            "FBR89wfP",
            "TJJW7obK",
            "7E04z2U8",
            "HAJwFBZn",
            "OPPKgNeV",
            "VVrVcWhp",
            "BFBRhaXC",
            "lKYWhqkC",
            "LdnSXBJv",
            "JsPBk9D2",
            "jEcc3oeD",
            "nA5sZfGf",
            "jRVyUKY8",
            "8ItpOrV7",
            "7ufSkKLN",
            "QoLWOlxG",
            "cpkrsPFw",
            "OJg9cqcY",
            "l49IXVWi",
            "pKPuEdEP",
            "RMsnApuH",
            "CXvLVgl9",
            "GaH78cY7",
            "v7pA8J7t",
            "MYree5Ze",
            "xHUskLV0",
            "Nq97d3KO",
            "Wpmgtymq",
            "be40ANs1",
            "JkGdHWlu"
        ];

        foreach ($names as $index => $name) {
            User::create([
                'name' => $name,
                'furigana' => $furiganas[$index],
                'email' => $emails[$index],
                'password' => Hash::make($passwords[$index]),
            ]);
        }
    }
}
